### ISSUE TITLE
Simplify system APIs

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#1152]
1. [ ] Unify the host-bindgen APIs used by “SimpleStateStorage” and “ViewStateStorage” (#1453, #1455)

    `contract_system_api.wit` and `service_system_api.wit` contain specific APIs only used by `SimpleStateStorage` and ultimately storing data in the map `ExecutionStateView::simple_users`.

    We should be able to remove these APIs and fix the modules `linera-sdk/src/{contract,service}/system_api.rs` so that the `SimpleStateStorage` feature is implemented on top of the same APIs as `ViewStateStorage` (e.g. `read_key` and `write_batch` from `view_system_api.wit`).

    This way, all user applications will use `ExecutionStateView::view_users` (to be renamed `ExecutionStateView::users` at the end).
2. [x] Remove locking primitive and disallow reentrancy by default (#1437, #1441)
3. [x] Make try_query_application_new synchronous (#1431)
