### ISSUE TITLE
Push Notifications Tracker

### ISSUE THREAD

**Issue by christos-h** [linera-io/linera-protocol#242]
## Features

- [x] `Notification` gRPC service between client and Proxy.
- [x] `Notifier` gRPC service between Proxy and server.
- [x] Eviction policy for `Notifier` holding references to dead connections.
- [ ] Restrict subscriptions only to chain owners.
- [x] Implement client for `linera-service/client`.

## Testing

- [x] End-to-end tests (client subscription, server notifier). This requires the client being implemented.
- [ ] Exclusive subscription test (clients can only subscribe to chains that they own)
- [x] Correctness of eviction policy for notifier.

## Benchmarking

- [ ] End-to-End load test to uncover potential performance bottlenecks.

**Comment by ma2bd** [comment]
Closing for now as the rest of the subtasks may not happen
