### ISSUE TITLE
Linera storage open-sourcing epic

### ISSUE THREAD

**Issue by MathieuDutSik** [linera-io/linera-protocol#244]
# Motivation

The goal is to summarize all the tasks necessary to release linera-view as a public crate.

# Tasks

## User interface improvements
- [x] #221 
- [x] #155
- [x] #256
- [x] #234 
- [ ] Minimize public APIs, notably decide if we remove the trait `Context` (not the struct)

## Data Types
- [x] #245
- [x] #247

## Performance optimizations
- [x] #241
- [x] #250
- [x] #246

## Database interface improvements
- [x] Support pagination of read/search queries in order to avoid the limitation in the size of queries (e.g. dynamoDb) #201 
- [x] #249
- [x] #248
- [x] #643

## Testing
- [ ] #251
- [ ] #252

## Documentation
- [ ] #253
- [ ] #254
- [x] #255

## Extensions
- [ ] Provide access to other databases like LevelDB
