### ISSUE TITLE
[Epic] Make `cargo doc` generate readable documentation for every crate in `linera-protocol`

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#378]
* [x] #1473
* [x] Finalize the inline (aka `cargo doc`) documentation for `linera-views`
* [ ] Finalize the inline (aka `cargo doc`) documentation for `linera-chain`
* [ ] Finalize the inline (aka `cargo doc`) documentation for `linera-storage`
* [ ] Finalize the inline (aka `cargo doc`) documentation for `linera-core`
* [ ] Finalize the inline (aka `cargo doc`) documentation for `linera-rpc`
* [x] #583
* [ ] Finalize the inline (aka `cargo doc`) documentation for `linera-service`
* [x] #389
