### ISSUE TITLE
Add a new crate to generate host WIT code

### ISSUE THREAD

**Issue by jvff** [linera-io/linera-protocol#906]
# Motivation

[`wit-bindgen`](https://github.com/bytecodealliance/wit-bindgen/) has recently been changed to only generate guest-side code. Host-side code must now be generated by separate crates specific for each Wasm runtime. Also, the generated host code didn't support reentrant calls.

# Solution

Create a new crate to generate the host side code for both the Wasmer and Wasmtime runtimes and that supports reentrant calls.

The new crate should also use Rust code as the source-of-truth, and support generating WIT files for `wit-bindgen` to use to generate the guest code.

## Merge plan

Since this new crate is non-trivial, merging it will be split into several PRs.

- [x] Create Witty crate (#880)
- [x] Represent WIT memory layouts (#886)
- [x] Create `WitType` trait (#890)
- [x] Add runtime and memory traits (#898)
- [x] Create `WitLoad` trait (#908)
- [x] Create `WitStore` trait (#915)
- [x] Add support for `enum`s (#921)
- [x] Create a `wit_import` macro (#944)
- [x] Add support for Wasmer (#945)
- [x] Add support for Wasmtime (#947)
- [x] Create a `wit_export` macro (#955)
- [x] Add support for reentrancy (#960)
- [x] Add support for extra user data (#1310)
- [ ] Generate WIT files from Rust code
  - #1704
  - #1902
  - #1910
